fixing prefix symbols
That script just made some nasty assumptions where our tools are.
It will infer the correct locations from the location of llvm-ld and klee itself, now.
These have to be in PATH.

diff --git a/scripts/prefix-symbols b/scripts/prefix-symbols
--- a/scripts/prefix-symbols
+++ b/scripts/prefix-symbols
@@ -7,5 +7,14 @@ if [[ "$unamestr" == 'Darwin' ]]; then
   ext="dylib"
 fi
 
-$LLVM_HOME/Release/bin/opt -load $KLEE/Release+Asserts/lib/prefix-symbols.$ext --llvm-prefix-symbols $@
+if ! which llvm-ld > /dev/null 2>/dev/null; then
+  echo "Error, LLVM bin dir not in path." 1>&2
+  exit 1
+fi
 
+if ! which klee > /dev/null 2>/dev/null; then
+  echo "Error, KLEE bin dir not in path." 1>&2
+  exit 1
+fi
+
+$(dirname "$(which llvm-ld)")/opt -load $(dirname "$(which klee)")/../lib/prefix-symbols.$ext --llvm-prefix-symbols $@
